### ISSUE TITLE
Installation fails macOS Ventura 13.0.1 version

### ISSUE THREAD

**Issue by AmanRaj1608** [ChainSafe/blst-ts#75]
Trying to install the lib on macOS Ventura 13.0.1 and getting error similar to https://github.com/ChainSafe/blst-ts/issues/70 

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/42104907/201945964-3f209083-2b70-418f-aac2-f712035c0531.png">

**Comment by dapplion** [comment]
@AmanRaj1608 Please can you post as text the full error until the very end?

**Comment by dapplion** [comment]
@AmanRaj1608 Our Github CI pipeline can't build the binaries for your architecture `darwin-arm64`, so they are attempted to be built locally.

The local build attempt fails because you don't have python installed
```
/bin/sh: python: command not found
make: *** [Release/obj.target/blst/geni/blst_wrap.cpp] Error 127
```

While we can't access `darwin-arm64` in a remote CI pipeline it's gonna be difficult for users of new MacOS to consume this packages

**Comment by AmanRaj1608** [comment]
Thanks @dapplion, fixed the python issue, builds locally now :)

**Comment by dapplion** [comment]
> Thanks @dapplion, fixed the python issue, builds locally now :)

Glad to know! Please re-open issue if you have problems. Could you paste here the command(s) you use to install / fix python linking? For reference for future users

**Comment by Pryority** [comment]
I can not build `@chainsafe/blst` on an M1 as well.

**Comment by dapplion** [comment]
> I can not build `@chainsafe/blst` on an M1 as well.

Can you paste the full error message you are getting? Please copy from invoking the command to the final line of your output
